# Generated by Django 5.1.4 on 2024-12-25 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account_type', models.CharField(max_length=10)),
                ('Account_number', models.IntegerField()),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.IntegerField()),
                ('Date_Time', models.DateTimeField(auto_now_add=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('E_Gift', models.BooleanField(default=False)),
                ('Expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Messages', models.TextField(blank=True, null=True)),
                ('payee_ID', models.IntegerField()),
                ('User_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('Customer_ID', 'payee_ID', 'Date_Time'), name='Customer_Transation_history')],
            },
        ),
    ]
