# Generated by Django 5.1.4 on 2024-12-25 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_balance_table_user_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_history',
            name='Messages',
        ),
        migrations.RemoveField(
            model_name='transaction_history',
            name='User_Id',
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
