# Generated by Django 5.1.4 on 2024-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_remove_transaction_history_messages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_table',
            name='Account_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='balance_table',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
