# Generated by Django 5.1.4 on 2024-12-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_balance_table_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_history',
            name='payee_ID',
            field=models.IntegerField(default=15),
        ),
    ]
