# Generated by Django 5.1.4 on 2024-12-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_transaction_history_payee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_table',
            name='Account_type',
            field=models.CharField(max_length=50),
        ),
    ]
